# Generated by Django 3.2 on 2023-02-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20230127_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguidores',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='seguidores',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='perfil',
        ),
        migrations.DeleteModel(
            name='seguidores',
        ),
    ]
